### ISSUE TITLE
How to reproduce the results in Table 1&2?

### ISSUE THREAD

**Issue by veronica320** [posgnu/rci#8]
Hi authors, 

Thanks for your excellent work! I'm wondering if you could provide more details on how to produce the results in Table 1 and 2, for example:

- Which LM did you use? (Section 3.1 said "InstructGPT-3 + RLHF", but which specific checkpoint?)
- What are the hyperparameters?
- What's the full prompt?
- Would it be possible to provide the dataset split/model predictions/relevant code in order to reproduce the results?

Thanks in advance!

**Comment by posgnu** [comment]
Hello,

We used the GPT-3.5 API for InstructGPT-3 + RLHF.

All the experimental setups were sourced from the Zero-shot-Cot repo (https://github.com/kojima-takeshi188/zero_shot_cot).
